spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/tacodb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true


