spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/tacodb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 189945765520-gkvtkviosig0p5fqmtl9jlh00me3qb8g.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

jwt:
  issuer: xkrghdud15967@gmail.com
  secret_key: taco-blog
